version: '3'
services:
  docker-app:
    build:
      context: .
      args:
        NODE_ENV: production
    ports:
      - "9000:9000"
    environment:
      - NODE_ENV=production
    command: node server.js