version: '3'
services:
  docker-app:
    build:
      context: .
      args:
        NODE_ENV: development
    ports:
      - "9000:9000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
    